// YouTube 자막 추출 유틸.
// InnerTube(iOS/WEB/Android) 플레이어 API로 공개 자막(ko 수동/asr)을 가져온다.
// 외부 패키지 없이 fetch만 사용해 Vercel 엣지/노드 어디서든 동작하게 한다.

export type TranscriptResult = {
    videoId: string;
    title: string;
    transcript: string;
    language: string;
    isAutoGenerated: boolean;
};

export function extractVideoId(urlOrId: string): string | null {
    const input = urlOrId.trim();
    if (!input) return null;

    if (/^[\w-]{11}$/.test(input)) return input;

    const match =
        input.match(/[?&]v=([\w-]{11})/) ||
        input.match(/youtu\.be\/([\w-]{11})/) ||
        input.match(/youtube\.com\/(?:shorts|live|embed|v)\/([\w-]{11})/);
    return match ? match[1] : null;
}

type InnertubeClient = {
    clientName: string;
    clientVersion: string;
    userAgent: string;
    extra?: Record<string, unknown>;
};

const CLIENTS: InnertubeClient[] = [
    {
        clientName: "IOS",
        clientVersion: "20.10.4",
        userAgent: "com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3 like Mac OS X)",
        extra: { deviceModel: "iPhone16,2" },
    },
    {
        clientName: "ANDROID",
        clientVersion: "20.10.38",
        userAgent: "com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip",
        extra: { androidSdkVersion: 30 },
    },
    {
        clientName: "WEB",
        clientVersion: "2.20250312.04.00",
        userAgent:
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0 Safari/537.36",
    },
];

type CaptionTrack = {
    baseUrl: string;
    languageCode: string;
    kind?: string;
};

function pickTrack(tracks: CaptionTrack[]): CaptionTrack | null {
    if (!tracks.length) return null;
    // 한국어 수동 자막 > 한국어 asr > 아무 자막
    return (
        tracks.find((t) => t.languageCode === "ko" && t.kind !== "asr") ||
        tracks.find((t) => t.languageCode === "ko") ||
        tracks.find((t) => t.languageCode.startsWith("ko")) ||
        tracks[0]
    );
}

function json3ToText(json: string): string {
    const data = JSON.parse(json) as {
        events?: { segs?: { utf8: string }[] }[];
    };
    const raw = (data.events || [])
        .flatMap((e) => e.segs || [])
        .map((s) => s.utf8)
        .join("");
    // ASR 자막은 같은 문장이 슬라이딩 윈도우처럼 반복 출력되므로 줄 단위 중복을 정리한다.
    const lines = raw
        .split(/\r?\n/)
        .map((l) => l.replace(/\s+/g, " ").trim())
        .filter(Boolean);
    const deduped: string[] = [];
    for (const line of lines) {
        const prev = deduped[deduped.length - 1];
        if (!prev || !prev.includes(line)) {
            // 이전 줄이 현재 줄의 앞부분이면(이어지는 문장) 이전 줄을 대체
            if (prev && line.startsWith(prev.slice(0, Math.min(prev.length, 40)))) {
                deduped[deduped.length - 1] = line;
            } else {
                deduped.push(line);
            }
        }
    }
    return deduped.join(" ").replace(/\s{2,}/g, " ").trim();
}

async function fetchWithTimeout(url: string, init: RequestInit, ms = 12000) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), ms);
    try {
        return await fetch(url, { ...init, signal: controller.signal });
    } finally {
        clearTimeout(timer);
    }
}

async function fetchPlayer(videoId: string, client: InnertubeClient) {
    const res = await fetchWithTimeout("https://www.youtube.com/youtubei/v1/player?prettyPrint=false", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "User-Agent": client.userAgent,
        },
        body: JSON.stringify({
            context: {
                client: {
                    clientName: client.clientName,
                    clientVersion: client.clientVersion,
                    hl: "ko",
                    gl: "KR",
                    ...(client.extra || {}),
                },
            },
            videoId,
        }),
    });
    if (!res.ok) return null;
    return res.json() as Promise<{
        videoDetails?: { title?: string };
        captions?: {
            playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] };
        };
    }>;
}

export async function fetchTranscript(urlOrId: string): Promise<TranscriptResult> {
    const videoId = extractVideoId(urlOrId);
    if (!videoId) {
        throw new Error("유효한 유튜브 링크가 아닙니다.");
    }

    let title = "";
    let track: CaptionTrack | null = null;
    let clientUA = CLIENTS[0].userAgent;

    for (const client of CLIENTS) {
        try {
            const player = await fetchPlayer(videoId, client);
            if (!player) continue;
            title = player.videoDetails?.title || title;
            const tracks =
                player.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
            const picked = pickTrack(tracks);
            if (picked) {
                track = picked;
                clientUA = client.userAgent;
                break;
            }
        } catch {
            continue;
        }
    }

    if (!track) {
        throw new Error(
            title
                ? `'${title}' 영상에 사용 가능한 자막이 없습니다. 영상 대본을 직접 붙여넣어 주세요.`
                : "자막을 찾을 수 없습니다. 영상 대본을 직접 붙여넣어 주세요."
        );
    }

    const res = await fetchWithTimeout(`${track.baseUrl}&fmt=json3`, {
        headers: { "User-Agent": clientUA },
    });
    if (!res.ok) {
        throw new Error("자막 다운로드에 실패했습니다. 대본을 직접 붙여넣어 주세요.");
    }
    const json = await res.text();
    const transcript = json3ToText(json);
    if (!transcript) {
        throw new Error("자막이 비어 있습니다. 대본을 직접 붙여넣어 주세요.");
    }

    return {
        videoId,
        title,
        transcript,
        language: track.languageCode,
        isAutoGenerated: track.kind === "asr",
    };
}
